### ISSUE TITLE
[BUG] Black Screen When Maximized on haitu.tv

### ISSUE THREAD

**Issue by Steven94Yan** [trophygeek/universalvideomaximizer#51]
Fill out what you can below

**Describe the bug**
Not sure if this is just me, but happens to me on quick a few pages, the screen turns black when it's maximized, sites like Youtube are still working correctly.

[A clear and concise description of what the bug is.]
INCLUDE SITE OR URL DETAILS LIKE:
- Which specific page is having the issue?
https://www.haitu.tv/vod/play/id/5666/sid/1/nid/24.html
- Does site require signup or paid subscription?
No
- Is it region restricted (some sports sites won't work from the US where author is from)?
Not region restricted, at least for US.
- Language if non-English?
The website is in Chinese.
- Maybe other extensions that might be running on page?

***SCREENSHOT OR VIDEO***
Removed video

[Very helpful to see a screenshot or video. You can drag upload them into this bug. 
If it's an adult site or may require login, then you should email me directly trophygeek@gmail]

**Steps to Reproduce if complicated**

(_Example_)
1. Go to ____
2. Click on ____
3. Scroll down to ____
4. See error ____

**Expected behavior**
[A clear and concise description of what you expected to happen.]
Video continue playing without turning into black screen.

**Help Version info:**

- Chrome: [ 117.0.5938.150 (Official Build) (64-bit) (cohort: Stable) ] `chrome://version/`
- OS: [ Windows 10 Pro 22H2] (Windows, Mac, Linux, ChromeOS) 
- Extension: [ 3.0.111] (can be found in the chrome extensions Details)

**Comment by trophygeek** [comment]
Good news: I was able to reproduce the problem.
More good news: It should be fixed in the next release.

I will update this bug when the store has the next update deployed (it can take some time).

**Comment by Steven94Yan** [comment]
excellent, thank you!

**Comment by trophygeek** [comment]
This version has finally been updated in store. Let me know if it fixes the issue you're seeing.

**Comment by Steven94Yan** [comment]
Just to confirm the version number is 3.0.112.

It no longer zooms the video, also disabling advanced feature doesn't remove the playback speed control panels anymore. (I just want a simple zoom and unzoom button. 

https://github.com/trophygeek/universalvideomaximizer/assets/22750166/b4d9de18-c35d-4b7c-8f4b-b60cae347eac

**Comment by trophygeek** [comment]
Thanks for the video. It's very helpful.

Yeah. I broke this feature when I removed the tutorial feature. "Simple mode" should be working again. Latest version is 3.0.115

**Comment by Steven94Yan** [comment]
can confirm the "simple mode" is working (no playback speed control anymore), but the video is still not zoomed when it's activated.

**Comment by trophygeek** [comment]
Umm... Let me double check it. 

Making all sites zoom can be tricky. Fixing one site often breaks another and there's NOT consistent way sites embed videos. Many put them in iframe.

To make everything MORE difficult, it's almost impossible to write tests for extensions that inject code into sites.

**Comment by trophygeek** [comment]
OK. Confirmed it's broken again. Not sure if the site changed or it's something in the extension.

I'll dig into some more and leave this bug open.
